### ISSUE TITLE
モデレータ・管理者であることは表示するべきか

### ISSUE THREAD

**Issue by atsu1125** [sakura-tel/areionskey#1068]
## 💡 Reason

・管理者であることはAPI応答・アイコンで識別可能
・モデレータであることはAPI応答のみで識別可能

個人単位もしくはインスタンス単位で隠せるようにするべきか、
そもそも開示しないようにするべきか

見せるならモデレータもアイコンを出してもよさそうではあるが、
見せないならモデレータであることはAPI応答から隠すべき

**Comment by fs5m8** [comment]
モデレータはプロフィールページにバッジをのっけていればそれでいいかなーと思ってる

**Comment by fs5m8** [comment]
@atsu1125 のフォークからもってくるわ

**Comment by fs5m8** [comment]
close https://github.com/sakura-tel/areionskey/commit/7498f775f1e7a8409d4e2cc2dbd41aa5497e9fb3
