### ISSUE TITLE
モデレータの操作範囲を区別する

### ISSUE THREAD

**Issue by atsu1125** [sakura-tel/areionskey#1069]
## 💡 Reason
現状管理者とモデレータの違いは
・管理者はモデレータを選任・解任できる
・管理者は管理者バッチが表示される
だけである

しかし通常であればモデレータは管理者と同等の権限を持たない
そのためめいすきー(あつが先日コミットしたやつ)とv12と同じように
`admin/update-meta`の操作には管理者権限を持たせるようにすることが望ましいように感じられる

問題（v12と異なる点）としては
・モデレータがインスタンスブロックを編集できなくなること - これはv11固有の問題
・モデレータがお知らせを編集できなくなること - めいすきーとv11で生じる問題

エンドポイントを変えることで対応は可能であるし
管理者が操作するものであると解釈することも可能

**Comment by atsu1125** [comment]
モデレータがDBバキュームできちゃあかんのかな
そっちも必要ならふさぐ

**Comment by fs5m8** [comment]
DBバキュームも塞いだほうがいいとおもう

**Comment by fs5m8** [comment]
moderator は大抵実際のサーバの鯖缶ではないことがほとんどなので

**Comment by atsu1125** [comment]
対応した
モデレータがAdmin用のMetaを取得するのも防止した
