### ISSUE TITLE
UserStatus: プレミアムアカウント・公式アカウント表示周りの完成度を上げる

### ISSUE THREAD

**Issue by fs5m8** [sakura-tel/areionskey#110]
## 理由
- シンボル・並びの統一を行うことにより，わかり易さと見た目の向上を図るため

## 行うこと
- i18n
   - ロケールファイルに「プレミアムアカウント」の表記内容を 追加する
- Common, ノートヘッダ
   - 公式アカウント表示を プレミアムアカウント表示 と admin表示 の間に 移動する
   - 公式アカウント表示を 星 から Font Awesome の認証マークに 変更する
   - プレミアムアカウント表示を 王冠 から Font Awesome の王冠に 変更する
   - プレミアムアカウント表示に マウスオーバした時の補足情報を 追加する
- Admin, ユーザ一覧
   - プレミアムアカウントにするボタン の王冠が表示されるように 修正する
   - 公式アカウント表示 と プレミアムアカウント表示 の位置を 交換する
   - 公式アカウント表示を 星 から Font Awesome の認証マークに 変更する
   - プレミアムアカウント表示を 王冠 から Font Awesome の王冠に 変更する
   - プレミアムアカウント表示にマウスオーバした時 補足情報が出るように 修正する

以下，追加有りましたらどうぞ

**Comment by remitocat** [comment]
問題なし
強いて言えば Font Awesome のバージョンを上げるかどうか

**Comment by fs5m8** [comment]
もうすでに最新じゃないの？

**Comment by remitocat** [comment]
まじ？

**Comment by fs5m8** [comment]
package.json 見たけど最新の見てるよ

**Comment by remitocat** [comment]
じゃあ大丈夫か

**Comment by fs5m8** [comment]
うん

**Comment by fs5m8** [comment]
## 行う場所
- i18n 
   - locales/en-US.yml
      - common:
   - locales/ja-JP.yml
      - common:
- Common, ノートヘッダ  
   - src/client/app/common/views/components/note-header.vue
      - tag.header, import, export default Vue.extend
- Admin, ユーザ一覧 
   - src/client/app/admin/views/users.vue
      - tag.div class="actions", import, export default Vue.extend
   - src/client/app/admin/views/users.user.vue
      - tag.header, import, export default Vue.extend

**Comment by Minemu398** [comment]
公式マーク、星じゃなくて蹄鉄ロゴにするのはどう？
表示は問題ないと思います
https://uma.milkey.homes/files/766b55e0-9c56-4456-a3dd-1601854286c2/766b55e0-9c56-4456-a3dd-1601854286c2.svg

**Comment by fs5m8** [comment]
採用

**Comment by fs5m8** [comment]
それどこの素材？faから？

**Comment by Minemu398** [comment]
ここ
https://icooon-mono.com/license/

**Comment by fs5m8** [comment]
了解

**Comment by fs5m8** [comment]
## 行うこと（202201062111）
- i18n
   - ロケールファイルに「プレミアムアカウント」の表記内容を 追加する
- **Client, Assets**
   - **icooon-mono の蹄鉄マーク を追加する** 
- Client, Common, ノートヘッダ
   - 公式アカウント表示を プレミアムアカウント表示 と admin表示 の間に 移動する
   - 公式アカウント表示を 星 から **icooon-mono の蹄鉄マーク**に 変更する
   - プレミアムアカウント表示を 王冠 から Font Awesome の王冠に 変更する
   - プレミアムアカウント表示に マウスオーバした時の補足情報を 追加する
- **Client, Common, みつける**
   - **公式アカウント表示を 星 から icooon-mono の蹄鉄マークに 変更する**
- Client, Admin, ユーザ一覧
   - プレミアムアカウントにするボタン の王冠が表示されるように 修正する
   - 公式アカウント表示 と プレミアムアカウント表示 の位置を 交換する
   - 公式アカウント表示を 星 から **icooon-mono の蹄鉄マーク**に 変更する
   - プレミアムアカウント表示を 王冠 から Font Awesome の王冠に 変更する
   - プレミアムアカウント表示にマウスオーバした時 補足情報が出るように 修正する

## 行う場所（202201062111）
- i18n 
   - mod - locales/en-US.yml
      - common:
   - mod - locales/ja-JP.yml
      - common:
- **Client, Assets**
   - **add - src/client/assets/horseshoe.svg** 
- Client, Common, ノートヘッダ
   - mod - src/client/app/common/views/components/note-header.vue
      - tag.header, import, export default Vue.extend
- **Client, Common, みつける**
   - **mod - src/client/app/common/views/pages/explore.vue**
      - **tag.mk-user-list :pagination="verifiedUsers", import, export default Vue.extend**
- Client, Admin, ユーザ一覧 
   - mod - src/client/app/admin/views/users.vue
      - tag.div class="actions", import, export default Vue.extend
   - mod - src/client/app/admin/views/users.user.vue
      - tag.header, import, export default Vue.extend

**Comment by remitocat** [comment]
蹄鉄アイコンはSVGで表示できるといいと思います
`src/client/assets` に配置して icooon-mono への直リンクは避けましょう (行う場所 への追加も忘れずに)

**Comment by fs5m8** [comment]
ほい

**Comment by fs5m8** [comment]
もう実装仕様、書いちゃっていい？

**Comment by Minemu398** [comment]
いいよ

**Comment by fs5m8** [comment]
Client, Admin, ユーザ一覧 の users.vue と Client, Common, みつける のアイコンを呼んでる部分の親が
Misskey のモジュールで，Font Awesome 前提の実装のため，Font Awesome 以外のアイコンへの変更が難しそうです

**Comment by fs5m8** [comment]
## 実装仕様書
- 追加 - src/client/assets/horseshoe.svg 
   - from https://icooon-mono.com/13481-%e8%b9%84%e9%89%84%e3%82%a2%e3%82%a4%e3%82%b3%e3%83%b31/

- 変更 - locales/en-US.yml
   - common:
      - 追加："premium-user" の en-US における i18n は "Premium Account" である

- 変更 - locales/ja-JP.yml
   - common:
      - 追加："premium-user" の ja-JP における i18n は "プレミアムアカウント" である

- 変更 - src/client/app/common/views/components/note-header.vue
   - tag.header
      - 変更：認証アカウント表示 "is-verified" の要素位置 は プレミアムアカウント表示 "is-premium" の要素位置 と Adminアカウント表示 "is-admin" の要素位置 の 間 とする
      - 変更：認証アカウント表示 "is-verified" の画像要素 は 画像 "src/client/assets/horseshoe.svg" を参照する
      - 追加：認証アカウント表示 "is-verified" の画像要素 は クラス "horseshoe" (新設) に属する
   - style
      - 追加：クラス "horseshoe" に属する要素 は 幅 1 em, 高さ 1 em, 垂直位置 -0.125 em である

- 変更 - src/client/app/admin/views/users.vue
   - tag.div class="actions"
      - 変更：認証アカウント表示の画像要素 は "faCrown" を参照する
   - import
      - 追加：@fortawesome/free-solid-svg-icons から モジュール "faCrown" を読み出す
   - export default Vue.extend - data
      - 追加："faCrown" を呼ばれた時に モジュール "faCrown" を渡すようにする

- 変更 - src/client/app/admin/views/users.user.vue
   - tag.header
      - 変更：認証アカウント表示 "is-verified" の要素位置 は プレミアムアカウント表示 "is-premium" の要素位置 と Adminアカウント表示 "is-admin" の要素位置 の 間 とする
      - 変更：認証アカウント表示 "is-verified" の画像要素 は 画像 "src/client/assets/horseshoe.svg" を参照する
      - 追加：認証アカウント表示 "is-verified" の画像要素 は クラス "horseshoe" (新設) に属する
   - style
      - 追加：クラス "horseshoe" に属する要素 は 幅 1 em, 高さ 1 em, 垂直位置 -0.125 em である

**Comment by fs5m8** [comment]
何かありましたらどうぞ

**Comment by remitocat** [comment]
問題なし

**Comment by fs5m8** [comment]
![image](https://user-images.githubusercontent.com/85814493/148632255-d653dcf9-8296-428e-b86a-12baf27684bf.png)
