### ISSUE TITLE
Admin: 他人の投稿を削除するステップを改善

### ISSUE THREAD

**Issue by remitocat** [sakura-tel/areionskey#114]
## 理由
自分の投稿を削除するステップと全く同じなので，Renote解除と勘違いしてしまう

ユーザーとして利用する場所と，モデレーション行為を行う場所を完全に分離するのが理想だと思います
タイムライン上では他人の投稿を削除できないようにして，その代わりに管理画面からノート単位でモデレーションできるようにするのが理想です
実装コストがかかるようであれば，他人の投稿を削除するときに限って警告を出すなどの暫定措置をとりたい

**Comment by fs5m8** [comment]
それ以外のモデレーションも，ユーザーとして利用する場所からできないようにしましょう

**Comment by fs5m8** [comment]
まず，とりあえず ユーザーとして利用する場所から 凍結・サイレンス ができないようにして，
他人の投稿を削除するときは いかなる設定であっても，ダイアログを出すようにしましょう
管理画面の変更は，別のissueで考える必要があると思います

**Comment by fs5m8** [comment]
atsuchan がばたばたしてるあいだにやってくれた
https://github.com/sakura-tel/areionskey/pull/913
