### ISSUE TITLE
バージョニングとプロジェクト名の見直し

### ISSUE THREAD

**Issue by remitocat** [sakura-tel/areionskey#115]
https://uma.milkey.homes/notes/8v7l525mka
> semverにおいて `-` はプレリリースを表すそうなので
> `11.37.1-milkey-* < 11.37.1` となってしまう

解決策
1. `11.38.0` から始める
2. `11.37.1-milkey-` を削除

**Comment by fs5m8** [comment]
でもこれ結局`x.y.z`のみになっちゃうんだよな…

**Comment by remitocat** [comment]
そうなんですよね
fork で `x.y.z` のバージョニングをする人はいるそうですが...
https://softwareengineering.stackexchange.com/questions/31551/forked-a-project-where-do-my-version-numbers-start

**Comment by fs5m8** [comment]
うーん，そうしましょうかね…

**Comment by remitocat** [comment]
それが妥協策ですかね... 仕方ないですが

プロジェクト名はどうしましょう
`package.json` では `misskey` になっていますが

**Comment by fs5m8** [comment]
名前変えたほうが良さそう
実装系変更するつもりだし

**Comment by remitocat** [comment]
名称はどうしましょう，umaMilkey かそれとも...

**Comment by atsu1125** [comment]
package.jsonのmisskeyを変えると既存のクライアントアプリからログインできなくなる恐れがあるかもしれないですね
Fedibirdもその理由でmastodonのままなので

**Comment by remitocat** [comment]
Groundpolisは `groundpolis` なんですよね
アプリでログインできるかどうかは検証していませんが...

**Comment by fs5m8** [comment]
同じのままだと混乱招きそうだなぁ

**Comment by remitocat** [comment]
こもはち名称考えてよ

**Comment by fs5m8** [comment]
_Areionskey（アレイオンスキー）_ （仮）

**Comment by remitocat** [comment]
仮ではなく確定でええやん

**Comment by fs5m8** [comment]
[確定] Areionskey（アレイオンスキー）

**Comment by remitocat** [comment]
それでは 私は本日22時以降にドキュメントを整備します
