### ISSUE TITLE
検索機能が使えない

### ISSUE THREAD

**Issue by remitocat** [sakura-tel/areionskey#12]
WebUIから検索すると400 Bad Requestとなってしまう
https://uma.milkey.homes/api/notes/search にアクセスするとNot Foundが返される

**Comment by remitocat** [comment]
URL (アカウント, 投稿) を入力した場合は正常に動作する

**Comment by sousuke0422** [comment]
v11はesが必須なので、うちとかv12からdb検索できる実装を拾ってくれば単体で完結する
