### ISSUE TITLE
MFMの検索ボックスが使えない

### ISSUE THREAD

**Issue by remitocat** [sakura-tel/areionskey#13]
タイトルの通り 検索ボタンを押すとGoogleのトップページに飛んでしまう

**Comment by fs5m8** [comment]
これ，環境によって挙動が異なるようで…

**Comment by remitocat** [comment]
なるほど
macOS Monterey の Vivaldi ではダメでしたね...
Chrome OSのChromeでも同様

**Comment by fs5m8** [comment]
https://www.google.com/search?q={{query}} でないと検索できない環境と
https://www.google.com/?#q={{query}} でないと検索できない環境が存在しているみたいで．
当方 Kubuntu 20.04.3 LTS 上の Firefox 95.0.1 / Nightly 97.0a1 では前者です

**Comment by remitocat** [comment]
そうなのか・・・
別の検索エンジンに変えたほうがいいかもしれませんね

**Comment by fs5m8** [comment]
ローカル上で動かした時には検索できるが，実際の uma.milkey.homes では検索できないっていう人もいるので，謎

**Comment by fs5m8** [comment]
https://duckduckgo.com/?q={{query}} とか使えますかね…？

**Comment by remitocat** [comment]
使えます！

**Comment by remitocat** [comment]
環境による差異がなければDuckDuckGoに変更ですかね...

**Comment by remitocat** [comment]
![image](https://user-images.githubusercontent.com/79707512/147338580-f4497e2c-bfe5-437a-8f44-7a865eaddef1.png)
あっ (設定→動作)
