### ISSUE TITLE
UserStatus: 猫耳の色を修正

### ISSUE THREAD

**Issue by remitocat** [sakura-tel/areionskey#130]
## 💡 Summary

猫耳の色がが場所によって異なるため、統一したい

<img width="280" alt="スクリーンショット 2022-01-14 10 49 14" src="https://user-images.githubusercontent.com/79707512/149437576-f59fa667-47bf-4077-a140-a1baddeef7ff.png">
<img width="311" alt="スクリーンショット 2022-01-14 10 49 25" src="https://user-images.githubusercontent.com/79707512/149437581-20e2beb5-ff6b-45b6-9ff9-81ac57704203.png">

## 行うこと

- `src/client/app/common/views/components/avatar.vue`
  * `.mk-avatar.cat` の `border-color` を `var(--bg)` に設定する

**Comment by fs5m8** [comment]
問題はなさそうです
ん〜 avatarColor は アバター の avgColor 取ってるんだろうけど，なんで色が変わるんだろ…？

**Comment by sousuke0422** [comment]
~~うちも同じ問題が上がってたので調査したところaタグか何かに色が当たって発生しているらしい
https://argon.teamblackcrystal.com/issue/AS-17
https://github.com/TeamBlackCrystal/misskey/commit/a5f1227fcd3f43967c816111ce2ac085567ad578~~

**Comment by sousuke0422** [comment]
と思ったけど、耳の色の算出方法がうちと多分違うので微妙に違いそう

**Comment by remitocat** [comment]
とりあえず応急処置としてやらせてください

**Comment by fs5m8** [comment]
あい

**Comment by remitocat** [comment]
`avgColor` を取るようにするのは別のissueで行いましょう

**Comment by fs5m8** [comment]
var(--bg) に変更するのはもう出来てるから一緒にcommitしちゃうね

**Comment by remitocat** [comment]
たすかる
