### ISSUE TITLE
[GPv2] プレミアム会員のドライブ増量機能

### ISSUE THREAD

**Issue by remitocat** [sakura-tel/areionskey#143]
支援してくださった方がいらっしゃるので早めに

**Comment by fs5m8** [comment]
from Groundpolis/gp2.0.2 as gp
- copy src/misc/get-drive-capacity.ts
- mod src/server/web/views/info.pug
  - insert L125-126 <- gp.L126-130
- mod src/server/api/endpoints/meta.ts
  - insert L143-144 <- gp.L133
- mod src/server/api/endpoints/drive.ts
  - insert L3-4 <- gp.L4
  - replace L40 <- gp.L41
- mod src/server/api/endpoints/admin/update-meta.ts
  - insert L138 <- gp.L139-145
  - insert L491 <- gp.L481-483
- mod src/services/drive/add-file.ts
  - insert L10-11 <- gp.L11
  - replace L314 <- gp.L330
- mod src/models/entities/meta.ts
  - insert L151 <- gp.L147-151 
- mod src/client/app/admin/views/instance.vue
  - insert L90-91 <- gp.L87
  - insert L283-284 <- gp.L280
  - insert L351-352 <- gp.L345
  - insert L479-480 <- gp.L470

**Comment by remitocat** [comment]
OK

**Comment by fs5m8** [comment]
作業中です
