### ISSUE TITLE
ログアウトできない

### ISSUE THREAD

**Issue by remitocat** [sakura-tel/areionskey#145]
## 💡 Summary

WebUI でログアウトボタンを押し、リロードされた後でもログアウトされないことがある
クライアントのキャッシュを削除すると正常に動作するが、クライアントの設定を消去してしまうため、危険である

## 📌 Environment

- Vivaldi 4.3.2439.65 (Stable channel) / macOS 12.0.1
- Google Chrome 96.0.4664.111 (Official Build) / Google Chrome OS 96.0.4664.111 (Official Build)

**Comment by remitocat** [comment]
ねこ

**Comment by fs5m8** [comment]
Firefox Browser 96.0 (Canonical) / Kubuntu 20.04.3 LTS
Firefox Nightly 98.0a1 (2022-01-18) / Kubuntu 20.04.3 LTS
Chromium 95.0.4638.54 (Official Build, ungoogled-chromium) / Kubuntu 20.04.3 LTS
では再現できませんでした

**Comment by remitocat** [comment]
謎は深まるばかり 🥴

**Comment by Minemu398** [comment]
M1MacのVivaldiからできませんでした
Safariからはできました

**Comment by Minemu398** [comment]
Firefoxでもだめ

**Comment by adzukyat** [comment]
https://user-images.githubusercontent.com/44765629/150380341-74a67a6f-3bc7-470c-833c-abbfb0b04b49.mp4

Windows 11 21H2, Google Chrome 97.0.4692.99 (64bit)

**Comment by atsu1125** [comment]
一応macOSとVivaldiとFirefoxのバージョン書いてください、バージョン依存の問題もあるため

**Comment by Minemu398** [comment]
macOS Monterey 12.1
Vivaldi 5.0.2497.43
Safari 15.2

**Comment by sousuke0422** [comment]
macOSのEdge駄目だけど、linuxのEdgeは問題なくログアウト可能

**Comment by fs5m8** [comment]
macOS 上の Gecko, Blink と Chrome OS はダメなのか…？

**Comment by ghost** [comment]
OS: Windows10 Pro 21H2
Browser: Chrome 97.0.4692.99(Official Build)(64bit)
で試したところ、ログアウト後の画面が一瞬表示されるものの、ログアウト前の画面にすぐ戻されてしまいログアウトできませんでした。

**Comment by sousuke0422** [comment]
WindowsのEdgeもダメみたいだからまともに使えるのLinuxだけじゃないかしら

**Comment by fs5m8** [comment]
https://github.com/mei23/misskey-v11/commit/4bb295d1e71cc75e2bdf88cbeb4470b5011c0976
