### ISSUE TITLE
Note: bug メンションと同じ行にカスタム絵文字があると，メンション先のアイコンが下にずれる

### ISSUE THREAD

**Issue by fs5m8** [sakura-tel/areionskey#168]

**Comment by fs5m8** [comment]
![image](https://user-images.githubusercontent.com/85814493/151089089-ffa7d94f-ddaa-42d3-9cf0-1e048cc74248.png)

**Comment by fs5m8** [comment]
https://github.com/sakura-tel/areionskey/commit/bacbb84e3cf273b71aa10e6ea1f39313aa4fa478#r64388239
https://github.com/sakura-tel/areionskey/commit/bacbb84e3cf273b71aa10e6ea1f39313aa4fa478#r64388480

**Comment by fs5m8** [comment]
あとこれもやっていい？

**Comment by remitocat** [comment]
いいよ

**Comment by remitocat** [comment]
Done ([573d4f7](https://github.com/sakura-tel/areionskey/commit/573d4f758c314aa2c5cf80ad123448722ac60966))
