### ISSUE TITLE
[Ayuskey] メンションにアイコンを表示

### ISSUE THREAD

**Issue by remitocat** [sakura-tel/areionskey#17]

**Comment by sousuke0422** [comment]
![image](https://user-images.githubusercontent.com/33174568/147340644-66c16b3c-05f1-4371-aede-cb363ddbc51d.png)
デザインが微妙なので調整が必要

**Comment by remitocat** [comment]
Ayuskeyで調整ができたらこちらも追従するようにしましょうか

**Comment by sousuke0422** [comment]
一度pickしちゃっていいと思う

**Comment by remitocat** [comment]
そうしましょう

**Comment by remitocat** [comment]
Done (bacbb84e3cf273b71aa10e6ea1f39313aa4fa478)
