### ISSUE TITLE
Note: KaTeX が使えない

### ISSUE THREAD

**Issue by fs5m8** [sakura-tel/areionskey#231]
## 💡 Summary
LaTeX のディスプレイ数式表記 `\[ ]\` 間に記述したことが表示されない

## 📝 How to fix
`src/client/app/common/views/components/formula-core.vue`
L8 `import * as katex from 'katex';` -> `import katex from 'katex';`

**Comment by remitocat** [comment]
草

**Comment by remitocat** [comment]
やっちまえ

**Comment by fs5m8** [comment]
草

**Comment by remitocat** [comment]
Done ([573d4f7](https://github.com/sakura-tel/areionskey/commit/573d4f758c314aa2c5cf80ad123448722ac60966))
