### ISSUE TITLE
Postform: Mobile UI での 引用あり・宛先・ローカル限定表示が左にはみ出る

### ISSUE THREAD

**Issue by fs5m8** [sakura-tel/areionskey#232]
## 💡 Summary
Mobile UI での 投稿フォーム の 引用あり・宛先・ローカル限定表示 が左にはみ出る

## 📝 How to fix
当該表示の 左 margin を調整する (8pxくらい）

**Comment by fs5m8** [comment]
`src/client/app/mobile/views/components/post-form.vue`
with-quote, to-specified, local-only の margin 値を 0 0 8px 0 -> 0 0 8px 12px

**Comment by remitocat** [comment]
OK
