### ISSUE TITLE
Header: アナログ時計が見にくい

### ISSUE THREAD

**Issue by fs5m8** [sakura-tel/areionskey#233]
## 💡 Summary
時計表示がダークモード寄りなのにも拘わらず，背景色が明るすぎる

## 📝 How to fix
`src/client/app/desktop/views/components/ui.header.clock.vue`
background の色を明るくする

**Comment by remitocat** [comment]
OK

**Comment by fs5m8** [comment]
Resolve https://github.com/sakura-tel/areionskey/commit/6cd315ec229265bf29d5a6a17c31cc70d3d30fb3
