### ISSUE TITLE
UserStatus: 猫耳の色をアイコンの平均色にする

### ISSUE THREAD

**Issue by fs5m8** [sakura-tel/areionskey#234]
https://github.com/sakura-tel/areionskey/issues/130

**Comment by wing-land** [comment]
これどうすればいいんでしょうね… そろそろ手をつけたいところです。

**Comment by fs5m8** [comment]
resolve https://github.com/sakura-tel/areionskey/commit/cd97f085fd230b13764422c3935b7ed6d06c699b
