### ISSUE TITLE
Postform: 改良

### ISSUE THREAD

**Issue by fs5m8** [sakura-tel/areionskey#302]
## 📝 How to fix
* Common: 引用ID を表示する
  * 左引用符 と 引用解除のバツボタン 間 に表示する
    * spanタグ で 変数 quoteId を表示させる
  * スタイルシート: 当該 spanタグ に 左margin は 4px, 色は`var(--text)`
* Desktop UI: ::-webkit-input-placeholder の削除
  * 標準化予定なし
* Mobile UI: -webkit-overflow-scrolling の削除
  * 標準化予定なし
* Mobile UI: 最近使用したハッシュタグ表示を枠内かつ上側へ移動
  * `div class="hashtags"` を Desktop UI から移植, `div class="with-quote"` の上に挿入
  * スタイルシート: `.hashtags` を Desktop UI から移植, `.with-quote` の上に挿入
    * `.hashtags` の margin: `0 0 8px 0` -> `0 12px 8px 12px`
* Mobile UI: 絵文字ピッカーアイコンに文字が被る
  * `textarea` の padding: `12px` -> `12px 32px 12px 12px`
* Mobile UI: ローカル表示・引用表示・DM表示 の右端の margin 調整
  * `.with-quote`, `.to-specified`, `.local-only` の margin: `0 0 8px 12px` -> `0 12px 8px 12px`

**Comment by fs5m8** [comment]
追記

**Comment by wing-land** [comment]
一通り確認しました。
`::-webkit-input-placeholder` は標準化の予定がないため削除が望ましいですが、WebKit 系のブラウザではプレースホルダーが表示されなくなるため、プレースホルダーが無くても入力の書式が分かるよう、十分に配慮する必要があると思います。
`-webkit-overflow-scrolling` は iOS 向けの設定ですが、2019年にリリースされた Safari 13 から不要となったため、削除するべきでしょう。
その他の項目について特記事項・問題点はありません。

**Comment by fs5m8** [comment]
スタイルシート部の `::-webkit-input-placeholder` を削除しても，規定のプレースホルダーの色に変わるだけですのであまり影響はないのではないかと考えています．

**Comment by fs5m8** [comment]
実際，`::-webkit-input-placeholder` が適用されない Gecko ではそのようになっていますし，WebKit系 で実例を参照したところ，それがなければ規定のプレースホルダーの色でレンダリングされています．

**Comment by fs5m8** [comment]
https://github.com/sakura-tel/areionskey/commit/dae78f311d0066536f87146e683033af2d262311
done
