### ISSUE TITLE
UserStatus: Nyaize で "na" を "nya" に変換しない

### ISSUE THREAD

**Issue by wing-land** [sakura-tel/areionskey#378]
## 💡 Reason
任意で ON/OFF を切り替えることができるようになる (#248) が、英単語中の "na" を "nya" に変換すると、本来の Nyaize の趣旨から外れてしまう場合があるため。
例: `native` -> `nyative`

**Comment by fs5m8** [comment]
* "na" を "nya" にする処理を削除

**Comment by wing-land** [comment]
破壊的変更ですので、皆さんのご意見をいただけると助かります

**Comment by fs5m8** [comment]
賛成
コミュニケーションツールにおいて，正しい意思疎通を阻害する実装はしないほうがよい．
日本語では，表記上「な」が「にゃ」になっていても，発音的には調音点を「に」と同じにした時の「な」が，「にゃ」であるので，どんな品詞中であってもやや苦しいが分かると思う．それを見越したお遊び実装であると思っている．
しかし，英語では `na` を様々な発音の仕方をする．例えば例示した `native` は `néɪṭɪv` である．`na` を `néɪ` (ネイ) と読んでいる．これを `nya` に置き換えてしまうと，ここでは発音的に語の意味が不明になってしまう上に，表記上でも表意文字ではないため，語の意味が不明になってしまうと思う．この文化がよく分かっていない方々にとってはなおさらである．

**Comment by wing-land** [comment]
もしかしなくても：v11 では na を nya に変換しておらず，everyone が everynyan になるような限定的な変換だけらしい
na -> nya は Groundpolis だけの実装か (すみませんでした

**Comment by wing-land** [comment]
やっぱりドキュメントの整備って大事やな...

**Comment by fs5m8** [comment]
つらすぎ
