### ISSUE TITLE
バージョンの付け方について

### ISSUE THREAD

**Issue by remitocat** [sakura-tel/areionskey#4]
今まで適当につけていましたが，共同開発をするにあたって共通したルールを作りたい

**Comment by remitocat** [comment]
参考：https://qiita.com/t_nakayama0714/items/c312bc5edcce6c214856

**Comment by fs5m8** [comment]
私の場合，昔は 2Aδ とか付けてましたけど，今は 2.3 のような形式で，
今は 一区切りつく or 変更する函数が数十個（リポジトリの規模による）を上回る変更をした or 破壊的変更をした → メジャーバージョンを上げる
それ以外 → マイナーバージョンを上げる のようにしています

**Comment by fs5m8** [comment]
ここの場合は3ケタ分ありますので，
1ケタ目 - 一区切りついた（やることなど lssue か どこかに書いておいて...）とき上げる
2ケタ目 - 機能が追加されたとき上げる
3ケタ目 - 小規模な修正をしたとき上げる
のようにすればいいのかな，と思っています

**Comment by remitocat** [comment]
それでいきましょう
元バージョンは11.37.1で変わらないので，`11.37.1-milkey-`を入れないほうがすっきりするような気もしますが，その辺はどうでしょう

**Comment by fs5m8** [comment]
元のバージョンがv11であるという情報は残したほうがいいのではないかと思います．
ホスティングサービスがどうなるかという話はまだ具体性を持っていませんが，
もし仮にv12以降のバージョンをフォーク・カスタムして提供するとすれば，
明確に分ける必要があると考えたからです．

**Comment by remitocat** [comment]
わかりました
それでは `v11.37.1-milkey-x.y.z` という形でバージョニングをすることにして，
どの桁を上げるべきかは https://github.com/sakura-tel/misskey-v11/issues/4#issuecomment-997371969 を参照することにしましょう

**Comment by remitocat** [comment]
この内容は今後Wikiに移設する予定です。
