### ISSUE TITLE
Note: 自分が付けたリアクションにマウスオーバーした時の表示

### ISSUE THREAD

**Issue by fs5m8** [sakura-tel/areionskey#97]
![image](https://user-images.githubusercontent.com/85814493/147405393-b075597f-284a-462e-aace-0b302227588f.png)
「が(reaction)をリアクション」としか出てこないので，自分のアイコンとユーザー名が出るようにしたい

**Comment by sousuke0422** [comment]
うちはv12とより近い実装にしたから克服したけど、`私は(プリンよりむしろ)寿司が好き`が使えなくなった

**Comment by fs5m8** [comment]
あ〜それどうしよ…

**Comment by fs5m8** [comment]
Resolve https://github.com/sakura-tel/areionskey/commit/1fae0a5aa4b6119c1bea38e3d2115495eddff992#
