### ISSUE TITLE
Note: 付いているリアクションにマウスオーバーした時のポップアップをv12っぽくしたい

### ISSUE THREAD

**Issue by fs5m8** [sakura-tel/areionskey#98]
今の表示だと見にくいと感じるので

**Comment by Minemu398** [comment]
どの辺が見にくいと感じる？表示される情報はV12と同じだと思うけど

**Comment by fs5m8** [comment]
- 「[名前] が [リアクション] をリアクション」の表示が冗長．
   - 音声読み上げ利用時には必要な情報なので，なんらかの形でその文言を埋め込む必要がある． 
- リアクションが見にくい時にマウスオーバーしても，結局見にくい．リアクションの表示が高さが1文字分しかないため．

**Comment by fs5m8** [comment]
resolve https://github.com/sakura-tel/areionskey/commit/203a4e6d63f08f9fb03fcb01e3ef06fe17245035
